### ISSUE TITLE
fix: solve forget password error

### ISSUE THREAD

**Issue by esau-morais** [esau-morais/django#12]
### Expected behavior

The user can use the "forget password" feature

### Actual behavior 

Error when the user tries to use "forget password"  feature

![Error](https://i.stack.imgur.com/mIVio.png)

### Guides

1. Fork this repository and clone

![Forking](https://camo.githubusercontent.com/6f03010c651d060f8b7cfc17da7098c1757c4ead/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f666f726b2e706e67)

`git clone github.com/user/Django.git`

2. Create a new branch called `forget-password` and publish

`git checkout -b forget-password `

3. Install the dependencies in `requirements.txt`

`pip install -r requirements.txt` or `pip3 install -r requirements.txt`

:warning: Make sure if the Python version is 3.6+

4. Start the app

`python manage.py runserver` or `python3 manage.py runserver`

**Comment by Palaash05** [comment]
I would be glad to work on this issue.

**Comment by esau-morais** [comment]
Go ahead!

**Comment by esau-morais** [comment]
Closed due to inactivity
